### ISSUE TITLE
Language code `C` on linux systems raises errors

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/glossary-client#7]
Error is:

> tests/unit/test_requests.py::test_requests_exception - ValueError: Invalid language code C found; 
> set locale or `default_language`

**Comment by jsvgoncalves** [comment]
@cmutel FYI https://github.com/sentier-dev/glossary-client/commit/0dbc40fbd5c199c389543967f5e75e487b633e46

**Comment by jsvgoncalves** [comment]
Assuming `C` to be `en_US` seems ok to me and not necessarily an error/warning.
